# filepath: docker-compose.yml

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile # Assumes root Dockerfile is for the backend
    ports:
      - "8000:8000" # Expose backend port
    volumes:
      # Mount backend code and necessary files/models
      - ./Backend:/app/Backend
      - ./yolov8n.pt:/app/yolov8n.pt
      # Add other necessary root files/models if backend uses them
      # - ./evaluation_model.py:/app/evaluation_model.py
    env_file:
      - ./Backend/.env # Load backend environment variables
    depends_on:
      - db
    # Ensure the command uses port 8000 if uncommented, or rely on Dockerfile CMD
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Set API URL to be relative for client-side calls, Nginx will proxy /api
        REACT_APP_API_URL: ""
    ports:
      - "80:80"   # Map host port 80 to Nginx container port 80
      - "443:443"  # Map host port 443 to Nginx container port 443 for HTTPS
    volumes:
      - ./certbot/www:/var/www/certbot:ro  # For ACME challenge files (read-only)
      - ./certbot/conf:/etc/letsencrypt:ro # For TLS certificates (read-only)
    depends_on:
      - backend # Ensure backend starts before frontend

  certbot-scheduler:
    build:
      context: ./certbot-scheduler
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # To allow executing docker commands
      - ./certbot/conf:/certbot/conf  # Mount certbot configuration directory
      - ./certbot/www:/certbot/www    # Mount certbot webroot for challenges
    depends_on:
      - frontend
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./Backend/.env # For POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    ports:
      - "5432:5432" # Expose PostgreSQL port if direct access is needed

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ./Backend/.env # For PGADMIN_DEFAULT_EMAIL, PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:80" # pgAdmin web interface
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: